export { default as Header } from './Header/Header'
export { default as Carousel } from './Carousel/Carousel'
export { default as Slider } from './Slider/Slider'
export { default as MovieCard } from './MovieCard/MovieSlide'
export { default as Footer } from './Footer/Footer'
export { default as SplitContainer } from './SplitContainer/SplitContainer'
export { default as Comment } from './Comment/Comment'
export { default as DetailCard } from './DetailCard/DetailCard'
export { default as ShowCard} from './ShowCard/ShowCard'